language: node_js
node_js:
- '0.10'
deploy:
  app: transport-staging
  provider: heroku
  api_key:
    secure: MF4fm+CWM3ASw9ECtO90ujy5MYw0rA96TJX7XJHkuHmq2iv6yY64JukadlgCVxVhptZhIOrvxuqvcG3VrdRdDJ1GaVbdCJn3aZ09+aQeHcKh/UQmeRPdxao8F16JVQxKuGYWeiYMAuC7BabIGw43vdxn7M4SVlMb3/uQ5HRnNnA=
